### ISSUE TITLE
No documented 'uninstall', cannot re-install after deleting directory

### ISSUE THREAD

**Issue by djtracy** [crestAT/nas4free-bittorrent-sync#1]
Title says it all:

I installed it once, but the thumb drive it was installed to was filling up from indexing my NAS. So, I deleted the directory (/mnt/DATA) it was installed to and everything seemed to be fine. Even the "Extensions" menu in my NAS4FREE web GUI disappeared.

However, any subsequent attempt to install it again somewhere else just hangs (no CPU usage).

**Comment by crestAT** [comment]
Sorry for the late reply, please install the most recent release which solves this issue.
