### ISSUE TITLE
cat: version.txt: No such file or directory

### ISSUE THREAD

**Issue by thorpj** [crestAT/nas4free-bittorrent-sync#2]
Running `/mnt/DATA/extensions/bts_install.php` gives this error (i replaced DATA with the correct file path, but for writing my fix here, i'll use "DATA"

Fixed by 
`cp /mnt/DATA/extensions/btsync/version.txt /mnt/DATA/extensions`
Restart
re run the two install commands

`cd /mnt/DATA/extensions && \
fetch https://raw.github.com/crestAT/nas4free-bittorrent-sync/master/bts_install.php && \
fetch https://raw.github.com/crestAT/nas4free-bittorrent-sync/master/bts-install.php && \
chmod 770 bts*install.php && \
echo "fetch OK"`

and 

`/mnt/DATA/extensions/bts_install.php`

**Comment by crestAT** [comment]
Sorry for the late reply, please install the most recent release which solves this issue.
